### PR TITLE
feat: Upgrade Ledger libraries and activate Clear Signing

### PR DESCRIPTION
**Pull request by lambertkevin**
Hi Rabby team !

According to the initiative of Ledger to activate clear signing on all possible Wallets with implementations of our stack, this PR should reactive everything related to:
 - Clear signing transactions (sending/approving ERC20/ERC721/ERC1155 & support for non standard contracts like 1inch, Paraswap and soon Uniswap via plugins if the user already has them installed on their device)
 - Clear signing EIP712 messages and falling back on method based on domain separator + message struct hash.

Issue raised by @heisenberg-2077 [here](https://github.com/LedgerHQ/ledger-live/issues/6065) has been fixed (sorry for the long delay 🙏) with this PR: https://github.com/LedgerHQ/app-ethereum/pull/559.
The next version of the Ethereum app will have this fix, and I'll ping you as soon as it's in prod 👍 

Feel free to tell me if I need to add some tests somewhere 👌

Thanks !

### CODE REVIEW

**Comment by heisenberg-2077** [comment]
Thanks for the fix!

I'm still getting error results with this PR.
Do I need to wait for a newer version of the Ethernet app before I can merge this PR?

**Comment by lambertkevin** [comment]
> Thanks for the fix!
> 
> I'm still getting error results with this PR. Do I need to wait for a newer version of the Ethernet app before I can merge this PR?

Yes, the PR has been merged for the new Ethereum app version, but I don't think we have released it yet, I'll make sure to ping you here once it's done so you can test it again before merging anything 👍

**Comment by vvvvvv1vvvvvv** [comment]
Let me know when this PR is ready for merge and release to production!
btw does this PR force require users to upgrade their firmware to use?

**Comment by lambertkevin** [comment]
Hi @vvvvvv1vvvvvv ! 
The PR should be ready to merge in about a month once we release the new Ethereum nano app, which will provide improvements for the EIP-712 clear signing and the fix for the bug reported by @heisenberg-2077. It's bit long, sorry about that, but we try to limit how many times we ask people to update theirs apps, so we packed a bunch of features and bugfixes  into a single release.
Regarding your second question, I'm not sure if the new nano app will be bonded with a specific firmware, so as far as I know for now, it shouldn't be required no. But updating the nano app will be required to have the new functionalities and the bugfix for sure 👍

**Comment by lambertkevin** [comment]
> @lambertkevin are there any updates on that, or expected release date?

Release for the new nano app is expected to be in about a month, after that we'll be able to merge this PR 👍

**Comment by vvvvvv1vvvvvv** [comment]
@lambertkevin any update on this?

**Comment by heisenberg-2077** [comment]
Hi @lambertkevin 

I tested this PR after updating my ledger.

The first run of signEIP712Message is ok, but after that it throws an exception `TransportStatusError: Ledger device: UNKNOWN_ERROR (0x6a00)`.
 I had to reopen the eth app on the ledger and call it again to get it to work.

Ledger NanoX V1.0
Firmware version: 2.2.4
Eth app version: 1.11.0

**Review by heisenberg-2077 — APPROVED** [review]

**Comment by vvvvvv1vvvvvv** [comment]
> We expect the PR to be ready to merge ~mid August with all final modifications, however the team is looking into a few edge cases where more logic needs to be added for transaction fallback. We'll circle back soon regarding how we should tackle those scenarios

Answer from Ledger side

**Comment by vvvvvv1vvvvvv** [comment]
We still waiting for update from Ledger team :(

**Comment by lambertkevin** [comment]
@0x398 We're still finding some bugs here and there and we're trying to address them as fast as possible. We have a release a new release scheduled this month, and hopefully this one should be good for an update of this PR 👍

**Comment by vvvvvv1vvvvvv** [comment]
going to close this PR since there is a new one https://github.com/RabbyHub/Rabby/pull/2545

**Pull request closed without merging**
