### PR TITLE
Add Language Support: pt-br

### PR DESCRIPTION
**Pull request by residenthiago2011**
Language Support for Brazilian Portuguese pt-BR for Rabby Wallet.
The order of the language was also changed, sorted by: Letter

### CODE REVIEW

**Comment by residenthiago2011** [comment]
PR Waiting Review and Approval.

**Comment by vvvvvv1vvvvvv** [comment]
sorted by: Letter in `code` is strange, we currently prefer sort by add time, so please change it back

**Comment by residenthiago2011** [comment]
Reverted Sort on Laguage Listing and Added pt_BR to Last one.

**Comment by vvvvvv1vvvvvv** [comment]
Awesome! Would you like to tell me your twitter id so we can mention you in the announcement twitter?

**Comment by residenthiago2011** [comment]
Glade to Help, my Profile is @residenthiago it's on my GitHub Profile too. Thanks

**Review by vvvvvv1vvvvvv — APPROVED** [review]

**Pull request merged**
