### PR TITLE
feat: Enable clear signing with Ledger devices

### PR DESCRIPTION
**Pull request by aussedatlo**
Hello Rabby team,

As part of Ledger's plan to enable clear signing on all Wallets that use our devices, this PR should reactivate everything connected to it.

This is a new version of #2280.

This PR aims to activate clear signing for:
- ERC20 transactions.
- Non standard contract transactions compatible with ledger devices through a plugin (1inch, paraswap..).
- EIP712 messages and falling back on method based on domain separator + message struct hash.

If the clear signing context is unreachable due to a poor connection (the plugin data can be large), a fallback system enables clear signing for common transactions. If no context is available, blind signing will be used instead.

Feel free to reach out to me with any questions.

Thanks !

### CODE REVIEW

**Comment by vvvvvv1vvvvvv** [comment]
image
What makes the bundle increase by 4MB?

**Comment by aussedatlo** [comment]
This might be related to the large size of [npm/@ledgerhq/cryptoassets@13.5.0](https://socket.dev/npm/package/@ledgerhq/cryptoassets/overview/13.5.0) dependency.

**Comment by vvvvvv1vvvvvv** [comment]
So this pakcage will become larger and larger as the number of supported chains and tokens increases, and it may include a lot of contract information in the future, until it grows to 100MB or 200MB?

**Comment by aussedatlo** [comment]
Great question. We use this large library as a fallback when internet data is unavailable. Currently, we are optimizing it by retaining only the most frequently used contexts, which should significantly reduce its size soon.

**Comment by vvvvvv1vvvvvv** [comment]
What is the final optimization goal? Like 500kb 200kb etc?

**Comment by aussedatlo** [comment]
700kb max

**Comment by vvvvvv1vvvvvv** [comment]
good, will merge the PR after optimization

**Comment by aussedatlo** [comment]
I've updated the `hw-app-dependency` to the latest version. The bundle size should be better now 👍

**Comment by vvvvvv1vvvvvv** [comment]
There is a wired issue with this PR:
- when I open Ethereum App, result of `navigator.getDevices` will be `[]`
- when I close Ethereum App, result of `navigator.getDevices` will be normal

with Ledger Stax(OS 1.5.0) and Ethereum App(version 1.12.1)

https://github.com/user-attachments/assets/2d46981d-fda1-4be5-912f-19fa6fbf31c1

**Comment by aussedatlo** [comment]
Can you also provide me the output of the `lsusb` command with and without the ethereum app opened ? 🙏

**Comment by vvvvvv1vvvvvv** [comment]
> Hello, I'm on it.
> To clarify, is your device functioning properly without these modifications? It appears that your browser is not detecting the device with the ethereum app. It is reproductible with another device ?

Yes, the device works fine without this PR

**Comment by vvvvvv1vvvvvv** [comment]
> Can you also provide me the output of the `lsusb` command with and without the ethereum app opened ? 🙏

when open Ehtereum App: `Bus 001 Device 005: ID 2c97:6000 2c97 Ledger Stax  Serial: 0001`
when close Ethereum App: `Bus 001 Device 004: ID 2c97:6015 2c97 Ledger Stax  Serial: 0001`
when device locked: `Bus 001 Device 004: ID 2c97:6015 2c97 Ledger Stax  Serial: 0001`

**Comment by aussedatlo** [comment]
Did you updated your ethereum app recently ? Can you try to re add your device with Rabby ?

**Comment by vvvvvv1vvvvvv** [comment]
Yes, I update Ethereum App before the issue happened, and it works well with this PR before the update.
The issue fixed after I add device to Rabby again, is it within expectation that user needs to add device again after update the Ethereum App?

btw I also run your code before add device again, it shows `No devices found`

**Comment by aussedatlo** [comment]
When you add a Ledger device through the browser, it saves the productId of the device to identify which device has been authorized by the user. Therefore, if the productId changes, you will need to reauthorize the device because the browser assumes it is a different device.

We are aware of this limitation with browsers and are working to ensure the productId remains consistent. The productId of the Ethereum app should be fixed with version 1.12.1. However, older versions can have different values, so this edge case may occur if a user previously registered their device with a different productId.

**Comment by vvvvvv1vvvvvv** [comment]
So this problem has nothing to do with this PR, it will happen as long as the Ethereum App is upgraded, right?
btw it happens on all devices or just Ledger Stax?

**Comment by aussedatlo** [comment]
This is unrelated to the PR, and I believe it can happen on all devices (I'm not sure, will check this), but it will be resolved in future versions.

**Comment by vvvvvv1vvvvvv** [comment]
OK fine, looks good to me, @he1m4n6a please help to do security audit of dependencies.
After that, we are fine to merge and release, @aussedatlo is it ready on your side?

**Comment by aussedatlo** [comment]
Yes ready on my side, thx !

**Comment by vvvvvv1vvvvvv** [comment]
should be today

**Pull request merged**
